In [ ]:
import numpy as np

# 1.
#m = np.array([[10,20,30,40],[50,60,70,80]])
m = np.arange(1,9).reshape(2,4)*10
m

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# 2.1
m[1,2]

7

In [ ]:
# 2.2
m[-1,-1]

14

In [ ]:
# 2.3
m[1:2,1:3]

array([[6, 7]])

In [ ]:
# 2.4
m[1:,2:3]

array([[ 7],
       [12]])

In [ ]:
# 2.5
m[0:2,-2:]

array([[3, 4],
       [8, 9]])

In [ ]:
# 3
f = m.reshape(-1,)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# 3.1
f[f%3==0]

array([ 0,  3,  6,  9, 12])

In [ ]:
# 3.2
f[f%4==1]

array([ 1,  5,  9, 13])

In [ ]:
# 3.3
np.logical_and(f%3==0, f%4==1)
f[np.logical_and(f%3==0, f%4==1)]

array([9])

In [ ]:
# 4.
m1 = np.eye(N=5,M=5,k=1)
m2 = np.eye(N=5,M=5,k=0)
m3 = np.eye(N=5,M=5,k=-1)
m1 + m2*2 + m3*3


array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [ ]:
# 5.
m = np.random.normal(0,1,30).reshape(5,6).round(4)

In [ ]:
# 5.1
np.max(m)

2.767746720098341

In [ ]:
# 5.2
np.sum(m, axis=1)

array([ 0.57545494,  5.82558926, -1.22308296,  3.67336774, -1.92464849])

In [ ]:
# 5.3
np.max(m, axis=1)

array([1.15917276, 2.76774672, 0.75420418, 2.00675564, 1.04957607])

In [ ]:
# 5.4
np.mean(m, axis=0)

array([ 0.24861732,  0.74323531, -0.59438539,  0.23551169, -0.03665095,
        0.78900811])

In [ ]:
# 5.5
np.min(m, axis=0)

array([-1.04718657, -0.47257287, -2.04249349, -1.28683719, -0.85544392,
        0.19694091])

In [ ]:
# 6.    그냥 정렬하면 다른차원 값이 바뀌어 버림
m = np.array([ [1,2,3,4], [46,99,100,71], [81,59,90,100] ])
m

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
 np.argsort(m[1])[::-1]

array([2, 1, 3, 0])

In [ ]:
# 엑셀처럼 정렬하기
m[:,np.argsort(m[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
# 7. 
import random
import numpy as np

a = np.arange(1,7,1)
m = [ random.choice(a) for i in range(100) ]

np.mean(m)

3.65

In [ ]:
np.unique(m)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 8. 
import matplotlib.pyplot as plt

price = 10000
exp = 0
std = 0.01
n = 250
rate = np.random.normal(exp, std, n)
price_list = []

for i in range(n):
    price += price * rate[i]
    price_list.append(price)

print(price_list)

[10058.152296486775, 10046.577373662965, 9987.061512775826, 9847.94113153937, 10012.626748030309, 9836.800951651836, 9932.089203424168, 10079.84596658618, 10205.288803870842, 10386.938464421459, 10341.802524409046, 10349.139656123047, 10439.448447068857, 10402.664674579572, 10372.401220178763, 10368.517136613971, 10383.722907109506, 10371.442806788422, 10419.914339700068, 10388.071311718835, 10449.289087093868, 10348.523744229153, 10499.606228808965, 10401.34169057657, 10395.823487044327, 10392.892896123523, 10408.249791232729, 10436.444008520924, 10552.589129512313, 10359.33200506202, 10201.814790511162, 10304.553902591735, 10289.631715134632, 10488.622442718932, 10663.86111525966, 10682.243871056278, 10691.43676497119, 10727.67189782102, 10675.992616994898, 10646.64316306172, 10499.758414603715, 10506.816211493471, 10559.949981923768, 10555.97076631298, 10450.193661544747, 10272.83962130966, 10328.044151953176, 10393.342840515143, 10522.01447224569, 10652.90655689927, 10617.224229142